[package]
name = "surch-index"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
surch-analysis = { path = "../surch-analysis" }
surch-codec = { path = "../surch-codec" }
surch-store = { path = "../surch-store" }
surch-types = { path = "../surch-types" }
serde_json = { workspace = true }
thiserror = { workspace = true }
